# Change these to your own values --

fork_this_github_user: harlantwood
fork_this_github_repo: Best-Practices
url: http://harlantwood.github.com/Best-Practices
root: http://harlantwood.github.com/Best-Practices
google_analytics_tracking_id: UA-17399272-1

# The rest of the default values should be fine, but can be changed if desired --

title: Best Practices & Tools
subtitle: "Use these or better..."
simple_search: http://google.com/search

permalink: none
# permalink: /:title
# permalink: /blog/:year/:month/:day/:title/

markdown: redcarpet
pygments: true

titlecase: false       # Converts page and post titles to titlecase
